title: Radley Brewing Co.
email: leon@radley.se
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site
markdown: kramdown

# Exclude from generation
exclude:
  - node_modules/

# Prefix posts with /blog
permalink: /blog/:categories/:year/:month/:day/:title/

# Custom collections
collections:
  beers:
    output: true
    permalink: /beer/:path/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "beers"
    values:
      layout: "beer"

# Global Variables
twitter_username: jekyllrb
github_username:  jekyll
